export const API_ENDPOINTS = {
  LOGIN: '/users/login',
  VERIFY: '/users/verify',
  REGISTER: '/users/register',
  GET_USER: '/users',
  GET_USER_BY_ID: (id: string) => `/users/${id}`,
  POST_TASK: 'users/tasks',
  GET_TASKS: 'users/tasks',
  DELETE_TASK: 'users/tasks',
  PATCH_TASK: 'users/tasks',
  SEND_FRIEND_REQUEST: '/friends/request/send',
  ACCEPT_FRIENDS_REQUEST: '/friends/request',
  REJECT_FRIENDS_REQUEST: '/friends/request',
  FRIENDS_REQUESTS: '/friends/request/received',
  REMOVE_FRIEND: '/friends/remove',
  GET_FRIENDS: '/friends/',
  GET_ME: '/users/me',
  DELETE_ME: '/users/me',
  GET_FRIEND_TASK: (id: string) => `friends/${id}/tasks`,
};
